travis:
  secure:
    BINSTAR_TOKEN: UeZzq0dgLlp/Dhj0BrPPTLSSpI8pGoDbN7s3eJQ5A22Q3SNziw297cS/mi9TgvjdTW9Tu3nTPeQshDW5TsP7Z8odL6ibohkBRs3/haphSufK9SRNqMgkBwVgYTSpBvhae/uPKxQWyCl93D3Kfc9drm07Dzt9tbPTdwt3WmSrEIJaZBCj7a4CURx3rx3zmtOUM2KA30ysc6k98gU0SXr/SuQbUyeSWQyP2GN4Rj8ZBbyqgGGNFIAbs3bT8/JlYbF2ejCybJfhoSa1wvN1+JdW9LIuMIGKeDCtGqHUE/qP0JRKy2V06BEGYVwYNHtnWjUWnFobwyYSzuxFKIMxIGOkddUCZUZy4C5UEz0gztKFKdaP+0i8jmXOhSKbeuYXpw8GRH4ZU1qunoSIsMYF8W2lvIxri2y36F1por3sATHmDiXnkfTHbI6DVctvI2cCqM86hQfOjmX4GF/aoPAzVTeWWxm0gTTOFs20S+ZOozT3eP8IHYz6s73nv0epOb9bjinFLtazpBczeLnI+XlUcsRQ/R6DTYydii2ly2Tqg45dc0iPbkkg+KB0qgMGR/ISmBKkjkwECOY9Or1YBVUNpV5rq+4jopGhstCYi2b62nuz7aizzjWIK1UzFmqXxLaklHcTnSugUdmR2AvYAf4s3W7VlB5JPY9ExXPWzIu3t9x6DNE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
