travis:
  secure:
    BINSTAR_TOKEN: sBcgv/axs6h+4NfDg8smoAoDsE6bYYznglyEOdOuetOiXeiQgFh2LaBZVDLKY26ajhntof9Jc+CTcFyLJ4KIH66pjTHZF2yOaA8hO5DGNL9cOv3rw1b71lo6peht2Hh9hN9ewcHOcvtSy01aG3khDET/xSQWDOmtPIAz7tzhBmpGDQHxRDMjqakggPP0upoGw40BUeMAXOh9hakl85xDNOmreVoVyblrrpGsIPaH8TYmMdLOAz9F8Go1QtYXW9tbxRcyp5hEpr+Qoc1lI6Tc0XT0NGgQdjoftt+exArBAfKjcm5Dgmi1JEAPUNvN84KCvV8bPVomO3qt7FUnk4WV+TzhIj8uevMTY/CtQpilBhsZ9JGuTYmMu3bIfJx9lp/WLK08ulj2ElTQQnQGHn8NrHdFkl9LSYE1JyA/Yb1STTrDEhm8LlhSjIHFQ67Edjhdwj7ZPSHDWf+M+sKxrnQHb6QyhuqWFwYnoBw0Sf0DxvuHKXQeZv9w3GhHrB996stIIatDQBQF61TLCHNiZH/uXd2JCFSvoZEQxlsfaYjzaiWMmsM3zWHCFfxpRXTWwVkmen65CUI9ewUQ2W6GO3F0F4zZAN2lctm8q0BSrlBZpqw9jmvtxDgxPottgiT3kWtlldq2Tt/++WqOxYeO2t1ARkQImwdFU/46E3kRK/H2A5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
